apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: foo@bar.com
    privateKeySecretRef:
      name: letsencrypt-nginx
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              key: access-token
              name: digitalocean-dns-token
