# This file defines the internal Tekton component dependencies
# It gets applied by the parent infra-configs kustomization

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-base
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/%($GITOPS_ENV)s/configs/tekton-config/base
  prune: true
  wait: true
  healthChecks:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonConfig
      name: config
      namespace: ""
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-tasks
  namespace: flux-system
spec:
  dependsOn:
    - name: tekton-base
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/%($GITOPS_ENV)s/configs/tekton-config/tasks
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-triggers
  namespace: flux-system
spec:
  dependsOn:
    - name: tekton-base
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/%($GITOPS_ENV)s/configs/tekton-config/triggers
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-rbac
  namespace: flux-system
spec:
  dependsOn:
    - name: tekton-base
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/%($GITOPS_ENV)s/configs/tekton-config/rbac
  prune: true

